type CountryNameMappingType = {
    [key: string]: string;
};

const countryNameMapping : CountryNameMappingType = {
    "mlt": "Malta",
    "prt": "Portugal",
    "alb": "Albania",
    "mkd": "North Macedonia",
    "dza": "Algeria",
    "tun": "Tunisia",
    "ago": "Angola",
    "npl": "Nepal",
    "ata": "Antarctica",
    "sol": "Solomon Islands",
    "arg": "Argentina",
    "zmb": "Zambia",
    "arm": "Armenia",
    "mng": "Mongolia",
    "aus": "Australia",
    "omn": "Oman",
    "aut": "Austria",
    "sau": "Saudi Arabia",
    "aze": "Azerbaijan",
    "che": "Switzerland",
    "bhs": "Bahamas",
    "ury": "Uruguay",
    "bgd": "Bangladesh",
    "lbr": "Liberia",
    "blr": "Belarus",
    "mli": "Mali",
    "bel": "Belgium",
    "mmr": "Myanmar",
    "blz": "Belize",
    "nic": "Nicaragua",
    "ben": "Benin",
    "pry": "Paraguay",
    "btn": "Bhutan",
    "rus": "Russia",
    "rus@europe": "Russia (Europe)",
    "rus@asia": "Russia (Asia)",
    "bol": "Bolivia",
    "svk": "Slovakia",
    "bih": "Bosnia and Herzegovina",
    "sdn": "Sudan",
    "bwa": "Botswana",
    "tza": "Tanzania",
    "bra": "Brazil",
    "ukr": "Ukraine",
    "brn": "Brunei",
    "vnm": "Vietnam",
    "bgr": "Bulgaria",
    "lbn": "Lebanon",
    "bfa": "Burkina Faso",
    "ltu": "Lithuania",
    "bdi": "Burundi",
    "mwi": "Malawi",
    "khm": "Cambodia",
    "mex": "Mexico",
    "cmr": "Cameroon",
    "mar": "Morocco",
    "can": "Canada",
    "prk": "North Korea",
    "caf": "Central African Republic",
    "ncl": "New Caledonia",
    "tcd": "Chad",
    "nga": "Nigeria",
    "chl": "Chile",
    "pan": "Panama",
    "chn": "China",
    "phl": "Philippines",
    "col": "Colombia",
    "qat": "Qatar",
    "cog": "Congo",
    "kor": "South Korea",
    "cod": "DR Congo",
    "srp": "Serbia",
    "cri": "Costa Rica",
    "slb": "Solomon Islands",
    "hrv": "Croatia",
    "esp": "Spain",
    "cub": "Cuba",
    "swz": "Eswatini",
    "cyp": "Cyprus",
    "twn": "Taiwan",
    "cze": "Czech Republic",
    "tgo": "Togo",
    "dnk": "Denmark",
    "tkm": "Turkmenistan",
    "dji": "Djibouti",
    "gbr": "United Kingdom",
    "dom": "Dominican Republic",
    "vut": "Vanuatu",
    "tls": "Timor-Leste",
    "web": "World",
    "ecu": "Ecuador",
    "afg": "Afghanistan",
    "egy": "Egypt",
    "lso": "Lesotho",
    "slv": "El Salvador",
    "lby": "Libya",
    "gnq": "Equatorial Guinea",
    "lux": "Luxembourg",
    "eri": "Eritrea",
    "mdg": "Madagascar",
    "est": "Estonia",
    "mys": "Malaysia",
    "sgp": "Singapore",
    "eth": "Ethiopia",
    "mrt": "Mauritania",
    "flk": "Falkland Islands",
    "mda": "Moldova",
    "fji": "Fiji",
    "mne": "Montenegro",
    "fin": "Finland",
    "moz": "Mozambique",
    "atf": "French Southern Territories",
    "fra": "France",
    "guf": "French Guiana",
    "nam": "Namibia",
    "gab": "Gabon",
    "nld": "Netherlands",
    "gmb": "Gambia",
    "nzl": "New Zealand",
    "geo": "Georgia",
    "ner": "Niger",
    "deu": "Germany",
    "nor": "Norway",
    "gha": "Ghana",
    "pak": "Pakistan",
    "grc": "Greece",
    "png": "Papua New Guinea",
    "grl": "Greenland",
    "per": "Peru",
    "gtm": "Guatemala",
    "pol": "Poland",
    "gin": "Guinea",
    "pri": "Puerto Rico",
    "gnb": "Guinea-Bissau",
    "rou": "Romania",
    "guy": "Guyana",
    "rwa": "Rwanda",
    "hti": "Haiti",
    "ssd": "South Sudan",
    "hnd": "Honduras",
    "sen": "Senegal",
    "hun": "Hungary",
    "sle": "Sierra Leone",
    "isl": "Iceland",
    "svn": "Slovenia",
    "ind": "India",
    "som": "Somalia",
    "idn": "Indonesia",
    "zaf": "South Africa",
    "irn": "Iran",
    "lka": "Sri Lanka",
    "irq": "Iraq",
    "sur": "Suriname",
    "irl": "Ireland",
    "swe": "Sweden",
    "isr": "Israel",
    "syr": "Syria",
    "ita": "Italy",
    "tjk": "Tajikistan",
    "civ": "Ivory Coast",
    "tha": "Thailand",
    "jam": "Jamaica",
    "tto": "Trinidad and Tobago",
    "jpn": "Japan",
    "tur": "Turkey",
    "jor": "Jordan",
    "uga": "Uganda",
    "kaz": "Kazakhstan",
    "are": "United Arab Emirates",
    "ken": "Kenya",
    "usa": "United States",
    "kos": "Kosovo",
    "uzb": "Uzbekistan",
    "kwt": "Kuwait",
    "ven": "Venezuela",
    "kgz": "Kyrgyzstan",
    "sah": "Western Sahara",
    "lao": "Laos",
    "yem": "Yemen",
    "lva": "Latvia",
    "zwe": "Zimbabwe",
};

// Export the mapping for use in your code
export default countryNameMapping;
